services:
  - type: background
    name: telegram-quiz-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_new.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
    autoDeploy: true
    branch: main